-- One-time cleanup: delete false positive CONTRADICTS edges and abstract-topic artifacts
-- Run AFTER backup: cp data/memory.db data/snapshots/memory_pre_fix.db

-- Step 1: Delete CONTRADICTS edges where EITHER node is synthetic
DELETE FROM edges WHERE edge_type='CONTRADICTS' AND (
  source_id IN (SELECT id FROM nodes WHERE category IN ('lc-chunk', 'abstract-topic', 'working-memory', 'atomic-fact'))
  OR target_id IN (SELECT id FROM nodes WHERE category IN ('lc-chunk', 'abstract-topic', 'working-memory', 'atomic-fact'))
);

-- Step 2: Delete old abstract-topic nodes and their edges (regenerated by fixed kmeans)
DELETE FROM edges WHERE source_id IN (SELECT id FROM nodes WHERE category='abstract-topic') OR target_id IN (SELECT id FROM nodes WHERE category='abstract-topic');
DELETE FROM nodes WHERE category='abstract-topic';

-- Step 3: Rename metrics-snapshot milestones
UPDATE nodes SET category='metrics-snapshot' WHERE category='milestone' AND content LIKE 'METRICS SNAPSHOT%';
